<a href="https://colab.research.google.com/github/Priyasri0210/DS-problems/blob/main/Pandas_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
import numpy as np

In [30]:
students_df = pd.read_csv('/content/students.csv')

In [7]:
students_df.head()

,StudentID,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore
0,101,Alice,17,Female,Delhi,85,92,88
1,102,Bob,16,Male,Mumbai,78,74,81
2,103,Charlie,17,Male,Delhi,95,89,93
3,104,David,16,Male,Bangalore,65,70,72
4,105,Eva,18,Female,Chennai,90,95,94

In [8]:
students_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   StudentID     10 non-null     int64
 1   Name          10 non-null     object
 2   Age           10 non-null     int64
 3   Gender        10 non-null     object
 4   City          10 non-null     object
 5   MathScore     10 non-null     int64
 6   ScienceScore  10 non-null     int64
 7   EnglishScore  10 non-null     int64
dtypes: int64(5), object(3)
memory usage: 772.0+ bytes

In [9]:
students_df[['Name','City','MathScore']]

      Name       City  MathScore
0    Alice      Delhi         85
1      Bob     Mumbai         78
2  Charlie      Delhi         95
3    David  Bangalore         65
4      Eva    Chennai         90
5    Frank     Mumbai         82
6    Grace      Delhi         88
7   Hannah    Chennai         77
8      Ian  Bangalore         72
9    Jenny     Mumbai         84

In [10]:
students_df.loc[(students_df['City'] == 'Delhi')]

,StudentID,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore
0,101,Alice,17,Female,Delhi,85,92,88
2,103,Charlie,17,Male,Delhi,95,89,93
6,107,Grace,16,Female,Delhi,88,91,85

In [11]:
students_df.loc[(students_df['EnglishScore'] > 85)]

,StudentID,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore
0,101,Alice,17,Female,Delhi,85,92,88
2,103,Charlie,17,Male,Delhi,95,89,93
4,105,Eva,18,Female,Chennai,90,95,94
9,110,Jenny,16,Female,Mumbai,84,86,90

In [32]:
students_df['Average'] = (students_df['MathScore'] + students_df['ScienceScore'] + students_df['EnglishScore'])/3
students_df

,StudentID,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore,Average
0,101,Alice,17,Female,Delhi,85,92,88,88.333333
1,102,Bob,16,Male,Mumbai,78,74,81,77.666667
2,103,Charlie,17,Male,Delhi,95,89,93,92.333333
3,104,David,16,Male,Bangalore,65,70,72,69.000000
4,105,Eva,18,Female,Chennai,90,95,94,93.000000
5,106,Frank,17,Male,Mumbai,82,80,78,80.000000
6,107,Grace,16,Female,Delhi,88,91,85,88.000000
7,108,Hannah,18,Female,Chennai,77,68,79,74.666667
8,109,Ian,17,Male,Bangalore,72,75,70,72.333333
9,110,Jenny,16,Female,Mumbai,84,86,90,86.666667

In [13]:
students_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   StudentID     10 non-null     int64
 1   Name          10 non-null     object
 2   Age           10 non-null     int64
 3   Gender        10 non-null     object
 4   City          10 non-null     object
 5   MathScore     10 non-null     int64
 6   ScienceScore  10 non-null     int64
 7   EnglishScore  10 non-null     int64
 8   Average       10 non-null     float64
dtypes: float64(1), int64(5), object(3)
memory usage: 852.0+ bytes

In [14]:
students_df.sort_values(by='MathScore',ascending=False)

,StudentID,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore,Average
2,103,Charlie,17,Male,Delhi,95,89,93,92.333333
4,105,Eva,18,Female,Chennai,90,95,94,93.000000
6,107,Grace,16,Female,Delhi,88,91,85,88.000000
0,101,Alice,17,Female,Delhi,85,92,88,88.333333
9,110,Jenny,16,Female,Mumbai,84,86,90,86.666667
5,106,Frank,17,Male,Mumbai,82,80,78,80.000000
1,102,Bob,16,Male,Mumbai,78,74,81,77.666667
7,108,Hannah,18,Female,Chennai,77,68,79,74.666667
8,109,Ian,17,Male,Bangalore,72,75,70,72.333333
3,104,David,16,Male,Bangalore,65,70,72,69.000000

In [15]:
students_df.value_counts('City')

City
Mumbai       3
Delhi        3
Chennai      2
Bangalore    2
Name: count, dtype: int64

In [23]:
students_df.loc[(students_df['City'] == 'Mumbai') & (students_df['ScienceScore'] > 80)]

,StudentID,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore,Average
9,110,Jenny,16,Female,Mumbai,84,86,90,86.666667

In [24]:
students_df.loc[(students_df['Gender'] == 'Female') & (students_df['Average'] > 85)]

,StudentID,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore,Average
0,101,Alice,17,Female,Delhi,85,92,88,88.333333
4,105,Eva,18,Female,Chennai,90,95,94,93.000000
6,107,Grace,16,Female,Delhi,88,91,85,88.000000
9,110,Jenny,16,Female,Mumbai,84,86,90,86.666667

In [35]:
students_df['Grade'] = np.where(students_df['Average'] >= 90, 'A', np.where((students_df['Average'] >= 80) & (students_df['Average'] < 90),'B',
                       np.where((students_df['Average'] >=70) &(students_df['Average'] < 80),'C','D')))
students_df

,StudentID,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore,Average,Grade
0,101,Alice,17,Female,Delhi,85,92,88,88.333333,B
1,102,Bob,16,Male,Mumbai,78,74,81,77.666667,C
2,103,Charlie,17,Male,Delhi,95,89,93,92.333333,A
3,104,David,16,Male,Bangalore,65,70,72,69.000000,D
4,105,Eva,18,Female,Chennai,90,95,94,93.000000,A
5,106,Frank,17,Male,Mumbai,82,80,78,80.000000,B
6,107,Grace,16,Female,Delhi,88,91,85,88.000000,B
7,108,Hannah,18,Female,Chennai,77,68,79,74.666667,C
8,109,Ian,17,Male,Bangalore,72,75,70,72.333333,C
9,110,Jenny,16,Female,Mumbai,84,86,90,86.666667,B

In [38]:
students_df.groupby('City')['Average'].mean()
students_df.groupby('City')[['MathScore','ScienceScore','EnglishScore']].mean()

           MathScore  ScienceScore  EnglishScore
City
Bangalore  68.500000     72.500000     71.000000
Chennai    83.500000     81.500000     86.500000
Delhi      89.333333     90.666667     88.666667
Mumbai     81.333333     80.000000     83.000000

In [52]:
students_df[students_df['ScienceScore'] == students_df['ScienceScore'].max()]

,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore,Average,Grade
4,Eva,18,Female,Chennai,90,95,94,93.0,A

In [56]:
students_df = students_df.drop('StudentID',axis=1)
students_df

,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore,Average,Grade
0,Alice,17,Female,Delhi,85,92,88,88.333333,B
1,Bob,16,Male,Mumbai,78,74,81,77.666667,C
2,Charlie,17,Male,Delhi,95,89,93,92.333333,A
3,David,16,Male,Bangalore,65,70,72,69.000000,D
4,Eva,18,Female,Chennai,90,95,94,93.000000,A
5,Frank,17,Male,Mumbai,82,80,78,80.000000,B
6,Grace,16,Female,Delhi,88,91,85,88.000000,B
7,Hannah,18,Female,Chennai,77,68,79,74.666667,C
8,Ian,17,Male,Bangalore,72,75,70,72.333333,C
9,Jenny,16,Female,Mumbai,84,86,90,86.666667,B

In [58]:
students_df['PassesMath']= students_df['MathScore'].apply(lambda x: 'Yes' if x >= 75 else 'No')
students_df

,Name,Age,Gender,City,MathScore,ScienceScore,EnglishScore,Average,Grade,PassesMath
0,Alice,17,Female,Delhi,85,92,88,88.333333,B,Yes
1,Bob,16,Male,Mumbai,78,74,81,77.666667,C,Yes
2,Charlie,17,Male,Delhi,95,89,93,92.333333,A,Yes
3,David,16,Male,Bangalore,65,70,72,69.000000,D,No
4,Eva,18,Female,Chennai,90,95,94,93.000000,A,Yes
5,Frank,17,Male,Mumbai,82,80,78,80.000000,B,Yes
6,Grace,16,Female,Delhi,88,91,85,88.000000,B,Yes
7,Hannah,18,Female,Chennai,77,68,79,74.666667,C,Yes
8,Ian,17,Male,Bangalore,72,75,70,72.333333,C,No
9,Jenny,16,Female,Mumbai,84,86,90,86.666667,B,Yes

In [59]:
students_df.to_csv('Students_processed.csv')